### ISSUE TITLE
Hard Coded Title on Error Dialog?

### ISSUE THREAD

**Issue by ejc7f** [yariksav/vuetify-dialog#1]
Error dialog seems to have a hard coded title:

![image](https://user-images.githubusercontent.com/1855318/46908685-6e241280-cef4-11e8-92d1-28bb6fea8a9f.png)

**Comment by yariksav** [comment]
Hi, @ejc7f!
Thank you for your issue! This is my fault, because package is in initial state, my apologize  
Fixed in v0.0.10 https://github.com/yariksav/vuetify-dialog/commit/63dd15d10d32e0bafda3380faee738fb0c671867

**Comment by ejc7f** [comment]
Fix works great.  Thanks!
