### ISSUE TITLE
Unable to load it with NUXT

### ISSUE THREAD

**Issue by ChibiChanNya** [yariksav/vuetify-dialog#10]
I have setup your module using the NUXT instructions for my project. It builds correctly, but on attempting to render a page I get the following error:

<img width="1241" alt="imagen" src="https://user-images.githubusercontent.com/6617493/50795568-48f53500-1294-11e9-8aba-c62a3d35a86b.png">

I thought it was an issue with my Node version because of the nature of the error, but It has failed on both 10.0 and 11.6. vuedl is in my node_modules and contains those files.

EDIT: Attempting to load it as a plugin results in the same error, so it seems independent from NUXT.

**Comment by yariksav** [comment]
Can you provide code where you use vuetify-dialog? Any type information of bug will good, because it difficult to understand what are you doing
And I suppose nuxt (or node) should use vuetify-dialog.esm.js version instead of commonjs (*.cjs.js)

**Comment by ChibiChanNya** [comment]
I have fixed this issue by transpiling both vuetify-dialog and vuedl.

Here's the relevant seciton in my nuxt.config.js:

```javascript
build: {
    /*
    ** You can extend webpack config here
    */
    vendors: ['babel-polyfill'],

    transpile: [/^vue2-google.*/, /^vuetify-dialog*/, /^vuedl*/],
...
}
```

**Comment by yariksav** [comment]
Hi, @ChibiChanNya !
Thank you for found solution!
I've fixed this in vuetify-dialog/nuxt module,
Please install latest 0.1.10 version `npm i vuetify-dialog@latest`
And remove  transpile: [ /^vuetify-dialog*/, /^vuedl*/], from nuxt.config.js, it will work

**Comment by ChibiChanNya** [comment]
Thanks for the update @yariksav !!! I can launch my project now without requiring the transpile. However, another issue has now come up. I get this error whenever my dev server reloads. It seems to be running something it shouldn't on every reload.

<img width="1232" alt="imagen" src="https://user-images.githubusercontent.com/6617493/50927356-26425800-141d-11e9-8dce-71c5c255a683.png">

<img width="1207" alt="imagen" src="https://user-images.githubusercontent.com/6617493/50927391-44a85380-141d-11e9-8fbe-c4a8bb08fb4b.png">

Perhaps this can be fixed by changing the context/property settings? They aren't very well documented so I haven't messed with them.

**Comment by yariksav** [comment]
Hi, @ChibiChanNya! I will investigate and fix it tomorrow. I will need your help to test correct work

**Comment by ChibiChanNya** [comment]
Alright. I will be paying attention to notifications, thanks for all the hard work @yariksav! I'll be fine in the meantime since this only happens on refresh.

**Comment by yariksav** [comment]
Hi, @ChibiChanNya! Please check version vuetify-dialog@0.1.11, is the bug with double install fixed.

**Comment by ChibiChanNya** [comment]
It appears to be fixed, @yariksav! Thanks for fast responses. Seeing no major errors, though I am getting this warning on the server console. 
<img width="1247" alt="imagen" src="https://user-images.githubusercontent.com/6617493/51052868-98da4180-159d-11e9-8aae-e2a7f80c770c.png">

It doesn't seem to do anything bad, but it does have a typo and it comes from your code. Fix seems a bit weird but so far so good. Guess all set when you remove it.

**Comment by yariksav** [comment]
I putted this warning for understanding all situations how ssr installing vue components. It has wierd behavior, when vue tells component is not installed, but is does... I will remove this waning in next version) Please tell me if something will not work. Thanks

**Comment by yariksav** [comment]
I guess I've found the reason of this bug, and it is not because of vuetify-dialog. This is bug in your nuxt version 2.0.0, latest is nuxt@2.3.4. Please update it and bug will resolve

**Comment by yariksav** [comment]
Hi, @ChibiChanNya. Please update vuetify-dialog@0.1.12. This version should fix your issue

**Comment by yariksav** [comment]
closed by https://github.com/yariksav/vuetify-dialog/commits/908296a33e582616ac697a5b0a811dfd9679e25d

**Comment by ChibiChanNya** [comment]
Sorry for disappearing. I'm trying out the latest version now and I don't get any warnings or anything. GJ!! Even if it's already closed :p
