### ISSUE TITLE
key: false not working in actions

### ISSUE THREAD

**Issue by tminich** [yariksav/vuetify-dialog#101]
If you use false as a key (to emulate default behaviour) you get text back (in the example `'No'`) instead of `false` (`$dialog.confirm` is affected, not sure if others are)
```js
{
  actions: [{
    text: 'No', color: 'blue', key: false
  }]
}
```

**Comment by yariksav** [comment]
can you try
```
{
  actions: {
    false: {
      text: 'No',
      color: 'blue'
    }
  }
}
```

**Comment by tminich** [comment]
Works, thank you.
