### ISSUE TITLE
Dialog options documentation

### ISSUE THREAD

**Issue by lenkrasinski** [yariksav/vuetify-dialog#108]
I've tried to set width in the passed options, it didn't work.
How do you set min-width and width of a dialog?
Is there documentation on the supported options?

**Comment by lenkrasinski** [comment]
const result = await this.$dialog.showAndWait(EnvCmdWizard, params, options)

**Comment by yariksav** [comment]
Hi, @lenkrasinski, you can do it inside your component EnvCmdWizard 
```
export default {
  layout: ['default', { width: 800 }],
  ....
}
```

**Comment by lenkrasinski** [comment]
Thank you
