### ISSUE TITLE
How use html in notifications?

### ISSUE THREAD

**Issue by 4KDA** [yariksav/vuetify-dialog#110]
How use html in notifications (Alert)?

Replace in Alert component 16 line from  {{ text }} to v-html="text"?

**Comment by ikallali** [comment]
+1

**Comment by yariksav** [comment]
Sorry for delay. Released version 2.0.13

**Comment by sbernard31** [comment]
I'm using 
```javascript
$dialog.notify.error(message, {
      position: "bottom-right",
      timeout: 5000,
    });
```
but my message value contains some string which is considered as html.  (e.g. <3442>)
I would like the text was considered as plain text is there a way to do that ?

**Comment by ikallali** [comment]
You can use
` &lt;3442&gt;`

**Comment by sbernard31** [comment]
Yep I know but I need to escape all HTML character in my `message` variable. 
And [I didn't find any out of the box way to escape](https://stackoverflow.com/questions/40263803/native-javascript-or-es6-way-to-encode-and-decode-html-entities), so I'm asking myself if there is not an API or a better way to do that.
