### ISSUE TITLE
Add context

### ISSUE THREAD

**Issue by 4KDA** [yariksav/vuetify-dialog#114]
Hello! How can I globally add additional context in nuxt version? I have an axios instance and need to use it in dialog.

**Comment by yariksav** [comment]
in nuxt $axios must assign into context automatically.
But if you create own instance, then in nuxt plugin:
```
export default (ctx, inject) => {
  ...
  ctx.$dialog.context.axios = axios
}
```
or
```
 Vue.prototype.$dialog.context.axios = axios
```

**Comment by 4KDA** [comment]
Thanks! It works!
