### ISSUE TITLE
How can I modify the font-size of dialog text

### ISSUE THREAD

**Issue by TheColdVoid** [yariksav/vuetify-dialog#12]
How can I modify the font-size of dialog text?Is there a parameter?

**Comment by yariksav** [comment]
this version doesn't have this opportunity. I will add it in next ver. Also you can create you own component and use it in dialogs.

**Comment by yariksav** [comment]
By the way, you can set text as html string
      await this.$dialog.warning({
        text: '<span style="font-size: 24px">Do yo really want to exit?</span>',
        title: 'Warning',
   ...
})
or

**Comment by TheColdVoid** [comment]
OK,thanks
