### ISSUE TITLE
$i18n not available with custom Dialog

### ISSUE THREAD

**Issue by emulienfou** [yariksav/vuetify-dialog#121]
Hello there, just create a custom dialog an I cannot use `this.$t()` or `this.$i18n.t()` inside the custom Dialog component.

Here is an exemple on how I create a custom dialog:
```js
await this.$dialog.show(CustomDialog, {
   $i18n: this.$i18n // Workaround
})
```

```vue
<template>
  <DialogCard>
      {{ $t('test') }} <!-- Not working without the workaround -->
   </DialogCard>
</template>
<script>
import DialogCard from 'vuetify-dialog/src/components/DialogCard'
export default {
   props: {
     $i18n: Object // Workaround
   }
}
</script>
```

> Without this workaround, I receive the message: `"TypeError: Cannot read property 't' of undefined"`

**Comment by yariksav** [comment]
You need to set i18n into context param
https://github.com/yariksav/vuetify-dialog#vuetify-2

Vue.use(VuetifyDialog, {
  context: {
    vuetify
  }
})

if you use nuxt, you need to setup through plugin vuetify-dialog/nuxt

if you use native vue, then setup 
Vue.use(VuetifyDialog, {
  context: {
    i18n,
   ...
    vuetify
  }
})

**Comment by emulienfou** [comment]
Thanks @yariksav working fine
