### ISSUE TITLE
SCRIPT1003 error in IE

### ISSUE THREAD

**Issue by bigplum** [yariksav/vuetify-dialog#13]
As this issue: https://forum.vuejs.org/t/solved-ie11-script1003-expected-error/29843

My project which uses the Vuetify-dialog can not work in IE, until I remove the Vuetify-dialog module. So I think there may be some compatible issues in this module.

Thanks.

**Comment by yariksav** [comment]
Hi, @bigplum! "Cannot work" - it's a lot of information to solve problem :(
At least can you provide error messages or screenshot from console?

Unfortunately I don't have ie11 in mac, but I tried to open it in online [service]
(https://www.browserling.com/browse/win/8.1/ie/11/https%3A%2F%2Fppx57r3nnj.codesandbox.io%2F)
Therefore I see dialogs works fine with babel transformation

Did yo try to use transform version dist/vuetify-dialog.min.js?

**Comment by bigplum** [comment]
The console screenshot:
![image](https://user-images.githubusercontent.com/478469/51588024-baccb000-1f1d-11e9-9677-94545a3dd4d4.png)

![image](https://user-images.githubusercontent.com/478469/51587994-9670d380-1f1d-11e9-87c4-eae5b1d9389b.png)

**Comment by bigplum** [comment]
I tried the dist/vuetify-dialog.min.js just now, it also show this error.

**Comment by bigplum** [comment]
Hi, yariksav, some user reported it does not work in iOS 9/10. So I run a simulator in Xcode, it reproduced. I think it is the same problem as in IE.

![image](https://user-images.githubusercontent.com/478469/51649599-1780a700-1fc0-11e9-8a32-1f42664e2b1f.png)

**Comment by bigplum** [comment]
```
$ vue -V
3.2.1
$ node -v
v8.12.0
```

**Comment by yariksav** [comment]
Hi, @bigplum. You use webpack compilation, which transpose project code with related modules to any you want js versions. I suppose it's not vuetify-dialog's task to transpose to compatible with old browsers code.

**Comment by nayils** [comment]
![image](https://user-images.githubusercontent.com/15634639/57693522-a3a00280-7673-11e9-9cb3-b3fea8f733d8.png)

У меня та же проблема на IE11..

**Comment by pawel-marciniak** [comment]
@yariksav Is dist/vuetify-dialog.js should be transformed version? Because it contains ES6 short function syntax in few lines:
![image](https://user-images.githubusercontent.com/51244133/60645199-5b61bd00-9e38-11e9-878f-0a9f66b39807.png)

This is why our projects that using this package don't work in IE. Will you be able to fix this?

**Comment by yariksav** [comment]
Hi, @pawel-marciniak , please check version 0.3.7
node_modules/vuetify-dialog/dist/vuetify-dialog.cjs.js in ES5 syntax

**Comment by pawel-marciniak** [comment]
@yariksav then I don't have more ideas why it still doesn't work in IE, I even tried to attach it like this in my main app.js file:

`const VuetifyDialog = require('vuetify-dialog/dist/vuetify-dialog.cjs')`

And app.js is transpiled by Babel...

**Comment by pawel-marciniak** [comment]
I think the problem now is that even if I import `vuetify-dialog.cjs.js` which has ES5 syntax, it uses `vuedl` package inside it and probably uses some ES6 version of `vuedl`. Also I found this article which says that vendor packages are not transpilied by webpack: https://medium.com/thetiltblog/how-to-transpile-es6-vue-plugins-with-webpack-c5d4286a7737

**Comment by yariksav** [comment]
Hi, @pawel-marciniak. I rewrote builder to rollup and integrated vuedl into package. Can you check version 0.4.0-beta.1?
Don't forget to install  and use babel-polyfill for IE
Also I've splitted css from js, now you have to import it manually (if you don't use nuxt plugin)
import 'vuetify-dialog/dist/vuetify-dialog.css'

**Comment by pawel-marciniak** [comment]
Hey, @yariksav. I found some time today to test this version - thank you for your commitment to fix this :) but sadly it still don't work in IE, there are still some ES6 features in dist/ files, for example: 

`(...)async function(...)`

I don't know much about npm package development, but looking at some other packages, like vue-router, all files in dist/ folder has pure ES5 syntax, except some import/export syntax in .esm version. Maybe this article will help us better understand how this distribution files should be build - https://hackernoon.com/how-to-publish-your-package-on-npm-7fc1f5aae600
There are some informations about package building in "Entry Points" paragraph.
