### ISSUE TITLE
notify creates new column instead of overlay

### ISSUE THREAD

**Issue by laurent-brisbois** [yariksav/vuetify-dialog#132]
Hello everyone !

When using `$dialog.notify` like so :

```javascript
this.$dialog.notify.success(`Application '${application.verbose_name}' correctly uninstalled`, {
  position: 'top-right',
  timeout: 5000
})
```

It does this :

![image](https://user-images.githubusercontent.com/48165976/118470577-1894ef80-b707-11eb-8aba-ec36d928879b.png)

An new "column" is generated instead of putting the alert on overlay.

What could be the source of this error ?

with the `message` version:

```javascript
this.$dialog.message.success(`Application '${application.verbose_name}' correctly uninstalled`, {
  position: 'top-right',
  timeout: 5000
})
```
I don't have the problem...

**Comment by laurent-brisbois** [comment]
I have figured out that the CSS isn't applied for .vuedl-notification.. Is there a reason ?

**Comment by yariksav** [comment]
you have to import css manually
```
import 'vuetify-dialog/dist/vuetify-dialog.css'
```

**Comment by laurent-brisbois** [comment]
Ah yeah indeed I forgot about that  ! Thanks for the reminder 👍 .
