### ISSUE TITLE
How to close dialog from component?

### ISSUE THREAD

**Issue by otatar** [yariksav/vuetify-dialog#140]
Hi there, I have a component to change password:
`
<template>
  <v-card class="pa-2">
    <v-card-title>Change Password</v-card-title>
    <v-card-text>
      <v-form id="change-pass-form">
        <BaseInput label="Username" disabled />
        <BaseInputPassword label="Password" />
        <BaseInputPassword label="Repeat Password" />
      </v-form>
    </v-card-text>
    <v-card-actions>
      <v-spacer />
      <BaseDialogButton color="primary" type="submit" form="change-pass-form" title="Submit" />
      <BaseDialogButton title="Cancel" @click="onCancel"/>
    </v-card-actions>
  </v-card>
</template>
`

And I am starting dialog like this:
` const dialogInstance = await this.$dialog.show(ChangePassCard);`

Is there a way to close dialog from within component?

**Comment by yariksav** [comment]
Hi, to close within component just run this.$emit('submit') or , this.$emit('submit', {... someReturnData})

**Comment by otatar** [comment]
Hi there,

thank you, it is working. Anyway, I have just saw that I cannot access vuex store from dialog. It gives me that this.$store is undefined...is this something with v-dialog or I am wrong again...?

**Comment by otatar** [comment]
Sorry, find a solution to this.$store problem on: https://github.com/yariksav/vuetify-dialog/issues/65
Thank you
