### ISSUE TITLE
Change theme from light?

### ISSUE THREAD

**Issue by sm373373** [yariksav/vuetify-dialog#15]
I'm trying to use a dialog confirm box.  My nuxt/vuetify app uses dark theme, but I'm not sure why the dialog box comes up with the light theme.

`                const res = await this.$dialog.confirm({
                    title: 'Warning',
                    text: 'Are you sure you want to remove SQL Group ' + sqlGroup.SQL_ID
                });`

The div element for the card is:

`<div class="v-card v-sheet v-sheet--tile theme--light">`

which is not what I want, I'd want theme--dark.

How do I achieve this?  

Thanks.

**Comment by yariksav** [comment]
Hello, @sm373373. Thank you for issue. I've begun to fix it

**Comment by yariksav** [comment]
fixed in v0.3.1 version
