### ISSUE TITLE
Default parameters

### ISSUE THREAD

**Issue by nayils** [yariksav/vuetify-dialog#16]
Hello! I have a big project. It is not convenient to manually set parameters each time (position, duration, etc.). Can you add the ability to set default parameters when initializing vuetify-dialog?

For example:

```
import VuetifyDialog from 'vuetify-dialog';

Vue.use(VuetifyDialog, {
    'notify': {
        'timeout': 1000
    },
    'dialog': {
        icon: '',
        actions: ['ОК']
    }
});
```

**Comment by yariksav** [comment]
Hi! @nayils! Good request. Certainly! I will add this ability in one-two days

**Comment by nayils** [comment]
Thank! I will wait!

**Comment by yariksav** [comment]
Resolved in 0.3.3 https://github.com/yariksav/vuetify-dialog/commit/92bfb4f50019a73b11d3622deb7f18a2aa08816c
@nayils can you try it?

**Comment by nayils** [comment]
Wow! It's great! Thank!

**Comment by nayils** [comment]
I noticed that there is no possibility to add default parameters for simple windows (vuedl, this. $ Dialog.showAndWait) =)) You have to manually write for each window.

**Comment by yariksav** [comment]
Please explain more understandable

**Comment by nayils** [comment]
У меня есть много окон разного вида. Я хочу, чтобы они все были с одинаковыми свойствами. Но пока что мне приходиться руками писать для каждого подобного окна:

```
const result = await this.$dialog.showAndWait(EditForm, {
                    width: 900,
                    persistent: true,
                    scrollable: true
                });
```

It would be nice if you could set the default settings:
import VuetifyDialog from 'vuetify-dialog';

```
Vue.use(VuetifyDialog, {
    'dialog': {
                   width: 900,
                    persistent: true,
                    scrollable: true
    }
});
```

**Comment by yariksav** [comment]
Такие настройки лучше всего указывать в форме EditForm. Только она будет знать свою  предпочтительную длинну, persistent ли и тд.
Для этого существует способ передачи и настройки лейаутов
в EditForm 
```js
export default {
...
   layout: ['default', {
      width: 900,
      persistent: true,
      scrollable: true
  }],
...
}
```
Также можно использовать свои лейауты, посмотри как реализован компонент DialogLayout
Чтоб загрузить свой лейаут нужно $dialog.layout('mylayout', MyLayout), потом в EditForm прописываешь layout: 'mylayout', или layout: ['mylayout', { OPTIONS }]

**Comment by nayils** [comment]
Хах, ой, я не перевел сообщение=)) Спасибо большое за ответ, за помощь и за этот замечательный плагин, очень выручает=) Лучшей работы с диалоговыми окнами я не видел=)

**Comment by yariksav** [comment]
Пользуйтесь на здоровье! Если будут вопросы - пиши)
