### ISSUE TITLE
Update default options with method

### ISSUE THREAD

**Issue by danielchodusov** [yariksav/vuetify-dialog#18]
Hi! Is there any easy way how to update default options after plugin is installed? I would like to translate default button texts when locale is changed something like this:

```js
setI18n (lang = null) {
  this.$dialog.options = {
    actions: [this.$t('no'),  this.$t('yes')]
  }
}
```

Now I update components directly but having some method for changing default options would he great! :)

**Comment by yariksav** [comment]
Perhaps will be better to make action texts as functions?
```js
Vue.use(VuetifyDialog, {
   confirm: {
      actions: {
         true: {
            text: () => {
                return this.$t('Yes')
            },
            ...
        }
      }
   }
} 
```

**Comment by danielchodusov** [comment]
Hi @yariksav yes this would be definitely better! :)
