### ISSUE TITLE
Unknown custom element

### ISSUE THREAD

**Issue by mrcode86** [yariksav/vuetify-dialog#19]
Hi,

i follow the setup and when i try: 
`          this.$dialog.error({
              text: 'Cannot delete this item',
              title: 'Error'
          });`

i recive this:
[Vue warn]: Unknown custom element: <v-dialog> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
found in

---> <Confirmable> at Confirm.vue
       <Root>

[Vue warn]: Unknown custom element: <v-card> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
found in

---> <Confirmable> at Confirm.vue
       <Root>

[Vue warn]: Unknown custom element: <v-toolbar> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
found in

---> <Confirmable> at Confirm.vue
       <Root>

[Vue warn]: Unknown custom element: <v-icon> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
found in

---> <Confirmable> at Confirm.vue
       <Root>

[Vue warn]: Unknown custom element: <v-toolbar-title> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
found in

---> <Confirmable> at Confirm.vue
       <Root>

[Vue warn]: Unknown custom element: <v-card-text> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
found in

---> <Confirmable> at Confirm.vue
       <Root>

[Vue warn]: Unknown custom element: <v-card-actions> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
found in

---> <Confirmable> at Confirm.vue
       <Root>

[Vue warn]: Unknown custom element: <v-spacer> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
found in

---> <Confirmable> at Confirm.vue
       <Root>

[Vue warn]: Unknown custom element: <v-btn> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
found in

---> <DialogAction> at DialogAction.vue
       <DialogActions> at DialogActions.vue
         <Confirmable> at Confirm.vue
           <Root>

Did i missed something? :)

**Comment by yariksav** [comment]
How do you install vuetify? Perhaps you use a-la-carte logic. try to use as
import Vuetify from 'vuetify'

**Comment by ikuru9** [comment]
```javascript
import Vue from 'vue'
import Vuetify from 'vuetify/lib' // <-- this change
import 'vuetify/src/stylus/app.styl'

import VuetifyDialog from 'vuetify-dialog'

Vue.use(Vuetify, {
  iconfont: 'md'
})
Vue.use(VuetifyDialog)
```
```javascript
import Vuetify from 'vuetify'
```

**Comment by mrcode86** [comment]
Perfect, i forgot the import.
