### ISSUE TITLE
It does not work with nuxts.js

### ISSUE THREAD

**Issue by fjbardelli** [yariksav/vuetify-dialog#22]
I install it, register and when using it, it gives me this error

[Vue warn]: Unknown custom element: <v-card> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <Confirmable> at Confirm.vue
       <Root>

**Comment by zachjharris** [comment]
It does work with nuxt.js, include your code (nuxt config as well as the code where you are trying to create a dialog) if you aren't sure how to set it up.

**Comment by fjbardelli** [comment]
in

**Comment by fjbardelli** [comment]
I did the same, in a totally clean project, and I made the same mistake. I enclose the project, to see if you can reprocess the error.
Thanks

[dlg.zip](https://github.com/yariksav/vuetify-dialog/files/3080234/dlg.zip)

**Comment by yariksav** [comment]
https://github.com/yariksav/vuetify-dialog/issues/3#issuecomment-483821422

**Comment by fjbardelli** [comment]
With this configuration, the app goes, but the other controls of veutify, like the datatable, I have to add them or it is not necessary.

With this example, I do not put the icon and the warning is not yellow as in the examples of https://ppx57r3nnj.codesandbox.io/

       let res = await this. $ dialog.warning ({

         icon: 'file',
         text: 'Do you realy want to \
         delete item? ',
         title: 'Attention',
         actions: {
           false: {
             text: 'No',
             color: 'blue',
           },
           true: {
             color: 'red',
             text: 'Yes',
             handle: () => {
               return new Promise (resolve => {
                 setTimeout (resolve, 3000)
               })
             }
           }
         }
       })



import Vue from 'vue'
//import Vuetify from 'vuetify/lib'
import es from 'vuetify/es5/locale/es'
import colors from 'vuetify/es5/util/colors'
import '@mdi/font/css/materialdesignicons.css' // Ensure you are using css-loader

import Vuetify, {
  VBtn,
  VCard,
  VCardActions,
  VCardText,
  VCardTitle,
  VDialog,
  VSpacer
} from 'vuetify/lib'

Vue.use(Vuetify, {
  components: {
    VBtn,
    VCard,
    VCardActions,
    VCardText,
    VCardTitle,
    VDialog,
    VSpacer
  },
  lang: {
    locales: {
      es,
    },
    current: 'es',
   // iconfont: 'mdi',
  },
  theme: {
     primary: colors.blue.darken2,
    accent: colors.grey.darken3,
    secondary: colors.amber.darken3,
    info: colors.teal.lighten1,
    warning: colors.amber.base,
    error: colors.deepOrange.accent4,
    success: colors.green.accent3
  }
})

**Comment by fjbardelli** [comment]
Solved, missing add to the configuration

   VIcon,
   VToolbar,
   VToolbarTitle,

Thank you so much
