### ISSUE TITLE
Dialog params

### ISSUE THREAD

**Issue by nayils** [yariksav/vuetify-dialog#23]
Hey. The documentation is written

`const dialog = await this.$dialog.show(MyDialog, params, options)`

But I do not understand how these parameters and options look? Can you set an example? I want for example, that the width of the window is 600px.

**Comment by nayils** [comment]
Sorry.

It's params vuetify. Please, close topic=)

```
const dialog = await this.$dialog.show(EditForm, {
                    width: 900,
                    scrollable: true
                });
```

**Comment by yariksav** [comment]
Hello, @nayils!
Yes, you are right. You can set to second param all options and props of component

**Comment by yariksav** [comment]
Third param is not use now, I will change documentation

**Comment by Berkmann18** [comment]
For those who stumbled upon here and wondering "How do I pass props to the component in `this.$dialog.show` call", here's how:
```
this.$dialog.show(YourComponent, {
  somePropName: 'lorem',
  someOtherProp: '...',
})
```

It might not be the best place to write the above, but the comments above helped in finding this solution which doesn't seem to be in the docs.
