### ISSUE TITLE
No show Color & Icon

### ISSUE THREAD

**Issue by fjbardelli** [yariksav/vuetify-dialog#26]
This code works, but no show icons and color   ##title.

       let res = await this.$dialog.warning({
        title: 'Titulo',
        text: 'Cuerpo',
        persistent: true
      });
      if (res === undefined) {
        this.$dialog.notify.warning("Closed without select action");
      } else {
        this.$dialog.notify.info(`Your choice is ${res}`);
      }

**Comment by yariksav** [comment]
Peraps something wrong in your vuetify and font installation. Please see example code. Information is too few for understand

**Comment by fjbardelli** [comment]
This is my nuxt config of veutify plugin

**Comment by fjbardelli** [comment]
Solved, missing add to the configuration

   VIcon,
   VToolbar,
   VToolbarTitle,

Thank you so much
