### ISSUE TITLE
ShowDialog

### ISSUE THREAD

**Issue by fjbardelli** [yariksav/vuetify-dialog#27]
Is posible send parameter to dialog componet?

**Comment by yariksav** [comment]
Any example or description? I don’t understand

**Comment by fjbardelli** [comment]
For exxmple this.$dialog.show(editStudent, 1), where 1 is id of record en db to edit

**Comment by yariksav** [comment]
this.$dialog.show(EditStudent, { id: 1 })
in EditStudent:
asyncData ({ params }) {
   console.log(params)
}

**Comment by fjbardelli** [comment]
Works fine.

Thanks
