### ISSUE TITLE
Notification icon not settable?

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [yariksav/vuetify-dialog#28]
Hello, first of all thank you, this is an extremely useful project and it seems to work well, one small issue though:
In the docs it says we can set the icons for notifications, however I'm not seeing that happen.
It does work for dialogs no problem but using the same setting in a notification doesn't seem to do anything at all, is this supported?

For example this notify code won't show my icon, just the default one:

```
    this.$dialog.notify.warning("message", {
        position: "top-right",
        icon: "fa-exclamation-triangle",
        timeout: 7000
      });
```

However with a dialog it does work to show my icon, for example:

```
this.$dialog.warning({
      text: "Are you sure you want to delete this record?",
      title: "Delete",
      icon: "fa-exclamation-triangle"
    });
```

**Comment by yariksav** [comment]
Hi, @WhatFreshHellIsThis! Thank you for the issue, this icon need to add to component
https://github.com/yariksav/vuetify-dialog/blob/master/src/components/Alert.vue

**Comment by 4KDA** [comment]
Any news? I would also like this functionality.

**Comment by renathoaz** [comment]
@yariksav Could you add color and icon prop for the component ? I really need this feature, by the way thank you for the lib, it really saved me a lot of time.

```
           this.$dialog.notify.success(
            `Empresa ${item.nome_fantasia} removida.`,
            {
              position: "top-right",
              timeout: 3000,
              color: 'gray', //prop needed
              icon: 'mdi-check-circle'  //prop needed
            });
```

**Comment by yariksav** [comment]
added in 2.0.11 https://github.com/yariksav/vuetify-dialog/commit/6d2ec9f616f14afd754106b71b551c8c09a98aab

**Comment by yariksav** [comment]
Maybe need to calc icon from type notification automatically? Like it did in $dialog.warning, etc?

**Comment by 4KDA** [comment]
Yes, If props icon is not specified, then automatically from the notification type
