### ISSUE TITLE
How does it works ?

### ISSUE THREAD

**Issue by kl3sk** [yariksav/vuetify-dialog#3]
I will try this awesome plugin but I have errors
first my ide don't find the package
![image](https://user-images.githubusercontent.com/2953145/48314859-f4a14200-e5cf-11e8-9f07-6eb6bf20607d.png)

Then, maybe due to the first error
![image](https://user-images.githubusercontent.com/2953145/48314847-d63b4680-e5cf-11e8-93ba-f973543f420c.png)

What did I forgot ?

**Comment by yariksav** [comment]
Hi @kl3sk!
Did you install vuetifyjs framework correctly? Because your error log tells on absent exactly vuetify components.
Please read https://vuetifyjs.com/en/getting-started/quick-start

**Comment by kl3sk** [comment]
I was sure that was you answer and of course I did.
Every Vuetify components works.

**Comment by yariksav** [comment]
Can you try switch version of compiled package:
vuetify-dialog/dist/vuetify-dialog.js
vuetify-dialog/dist/vuetify-dialog.cjs.js
vuetify-dialog/dist/vuetify-dialog.es.js
vuetify-dialog/dist/vuetify-dialog.min.js
and tell me is one of them will work

otherwise i would need to see your code :(

**Comment by kl3sk** [comment]
I’ve tried this too. 

I can’t give you code for now. But. I just copy your demo code inside mine. 

BTW there is some typo (missing quote)


No template seems needed ?

**Comment by xi-osman** [comment]
I have this issue too I think its because of how Vuetify is installed Vue CLI plugin

**Comment by yariksav** [comment]
can you please explain more detail information? What version of vue cli. The best case will be if you show me part of code where you use vuetify and vuetify-dialog

**Comment by xi-osman** [comment]
Found the issue when you install vuetify from the Vue CLI plugin **"vue add vuetify"** more info [here](https://vuetifyjs.com/en/getting-started/quick-start#vue-cli-3-install) it will import Vuetify with `import Vuetify from 'vuetify/lib'` instead of `import Vuetify from 'vuetify'`

**Comment by xi-osman** [comment]
So to fix it i had to update the file `src/plugins/vuetify.js`

![image](https://user-images.githubusercontent.com/463779/48807593-9cf78a80-ece3-11e8-8c75-d0737cfe6457.png)

**Comment by yariksav** [comment]
I've installced @vue/cli and vuetify preset, than I installed vuetify-dialog, 

```bash
vue create my-app
vue add vuetify
npm i vuetify-dialog
```

and modified file **src/plugins/vuetify.js**
```js
import Vue from 'vue'
import Vuetify from 'vuetify/lib'
import 'vuetify/src/stylus/app.styl'
import VuetifyDialog from 'vuetify-dialog'

Vue.use(Vuetify, {
  iconfont: 'md',
})
Vue.use(VuetifyDialog)
```
Everything works fine
 
By the way, in your screenshot you use vuetify-confirm instead vuetify-dialog

**Comment by kl3sk** [comment]
I agree @xi-osman's answer because it works as he said.

Just remove `/lib` from the `Vuetify` import.

**Comment by kl3sk** [comment]
Because a solution is found i close this issue for now.

**Comment by bigplum** [comment]
It spent me some time to fix this problem. So I think this issue should be mentioned in the project readme document.
Anyway, thanks yariksav for this awesome plugin.

**Comment by dafen** [comment]
I had the same issue and removing the `/lib` part works but I like to point out that this increases the bundle size significantly (for my project it jumped from around 120kb to almost 250gb gziped)

**Comment by yariksav** [comment]
I guess I have found solution
Just need to add components VBtn, VCard, VCardActions, VCardText, VCardTitle, VDialog, VSpacer manually:

```js
import Vue from 'vue'
import colors from 'vuetify/es5/util/colors'

import Vuetify, {
  VBtn,
  VCard,
  VCardActions,
  VCardText,
  VCardTitle,
  VDialog,
  VSpacer
} from 'vuetify/lib'

Vue.use(Vuetify, {
  components: {
    VBtn,
    VCard,
    VCardActions,
    VCardText,
    VCardTitle,
    VDialog,
    VSpacer
  },
  theme: {
    primary: colors.blue.darken2,
    accent: colors.grey.darken3,
    secondary: colors.amber.darken3,
    info: colors.teal.lighten1,
    warning: colors.amber.base,
    error: colors.deepOrange.accent4,
    success: colors.green.accent3
  }
})
```

**Comment by fjbardelli** [comment]
With this nuxt configuration, it works, but if I want to use other veutify components, like the datatable, I have to add it there or take it alone and I can use it without adding

import Vue from 'vue'
//import Vuetify from 'vuetify/lib'
import colors from 'vuetify/es5/util/colors'
import VuetifyDialog from 'vuetify-dialog'

import Vuetify, {
  VBtn,
  VCard,
  VCardActions,
  VCardText,
  VCardTitle,
  VDialog,
  VSpacer
} from 'vuetify/lib'


Vue.use(Vuetify, {
  components: {
    VBtn,
    VCard,
    VCardActions,
    VCardText,
    VCardTitle,
    VDialog,
    VSpacer
  },
  theme: {
    primary: colors.blue.darken2,
    accent: colors.grey.darken3,
    secondary: colors.amber.darken3,
    info: colors.teal.lighten1,
    warning: colors.amber.base,
    error: colors.deepOrange.accent4,
    success: colors.green.accent3
  }
})
