### ISSUE TITLE
Missing components under nuxt

### ISSUE THREAD

**Issue by ruudboon** [yariksav/vuetify-dialog#30]
When running the extension under nuxt I get errors like:
```
commons.app.js:13184 [Vue warn]: Unknown custom element: <v-snackbar> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
```

**Comment by yariksav** [comment]
you have to install VSnackbar and other vuetify components manually. Thats because you use a-la-carte installation.
Vue.use(Vuetify, {
components: {
VSnackbar,
...
}
}

**Comment by baccenfutter** [comment]
@yariksav I'm running into the same issue and I am not using a-la-carte. None of my dialogs are able to find their Vuetify components.

The `plugins/vuetify.js` of my Nuxt app:

```js
import Vue from 'vue'
import Vuetify from 'vuetify/lib'

Vue.use(Vuetify, {
  theme: { ... },
})
```

Shouldn't this install all Vuetify components? Do I have to install my components manually, anyway? 

This is how I configured `vuetify-dialog` in my `nuxt.config.js`:

```js
modules: [
  ['vuetify-dialog/nuxt', {
    property: '$dialog'
  }],
  ...
]
```

Vuetify itself is working perfectly fine within the rest of my project, only `vuetify-dialog` is unable to find its components.
