### ISSUE TITLE
SCRIPT5009: "Proxy" не определено

### ISSUE THREAD

**Issue by nayils** [yariksav/vuetify-dialog#31]
Привет. Пробую запуститься в ИЕ11 (с помощью babel 7), натыкаюсь на ошибку SCRIPT5009: "Proxy" не определено. Окошки не работают. Понимаю, что из-за проблем совместимости с Proxy в IE. Но есть ли возможность сделать реализацию минуя прокси? Тогда бы было меньше проблем с IE=)

Вот таблица, которая говорит, что с Proxy могут быть проблемы:
https://kangax.github.io/compat-table/es6/
 
![image](https://user-images.githubusercontent.com/15634639/57768564-17a2df00-7736-11e9-9b0b-b16e5df75f14.png)

А если использую babel 6, то ошибка:
SCRIPT1003: Предполагается наличие ':'

**Comment by yariksav** [comment]
попробуйте установить полифил
https://github.com/GoogleChrome/proxy-polyfill

**Comment by nayils** [comment]
Пробовал. Полноценно невозможно заполифилить прокси.. Поэтому все ровно ошибка. Есть возможность избавиться от прокси? Это бы расширило поддержку браузеров и соответственно пользователей плагина, потому что это реально самый удобный плагин для окон.

**Comment by yariksav** [comment]
Разве что делать отдельную версию плагина без прокси. Прокси там используется для автоматической подстановки компонентов по вызову функции, например, ты можешь зарегистрировать компонент LoginForm, и потом использовать как this.$dialog.LoginForm(options)
так работают confirm, prompt, error, warning,...
Мне надо изучить как это cделать отдельно от прокси...
всем этим занимается модуль dialogManager из пакета vuedl
https://github.com/yariksav/vuedl/blob/master/src/manager.js

**Comment by nayils** [comment]
Может быть можно как-то сделать не отдельную версию, а реализовать прокси своими средствами внутри плагина?

**Comment by yariksav** [comment]
Убрал прокси. Пробуйте версию 0.3.5.
