### ISSUE TITLE
Vuetify PR

### ISSUE THREAD

**Issue by robsontenorio** [yariksav/vuetify-dialog#32]
Hi @yariksav ! Nice job!

I was wondering if this can be merged on vuetify framework? There are many issues requesting this features.

https://github.com/vuetifyjs/vuetify/issues/3037

**Comment by yariksav** [comment]
Hi, @robsontenorio! I suppose it can't be merged into vuetify, because this is separate module with self dependencies, tests and logic.
Why not use as additional module? )
