### ISSUE TITLE
Prompt autofocus works only once

### ISSUE THREAD

**Issue by enf644** [yariksav/vuetify-dialog#33]
Unfortunately when you prompt second time, the autofocus on v-text-field does not fire.
It can be seen in your [demo sendbox](https://ppx57r3nnj.codesandbox.io/).

Is there a way to make it work or maybe manually focus on input after dialog is opened?

Additionally - is there a way to modify prompt buttons style? 
They are different from buttons of confirm dialog. Is this is a error or made on purpose?
Thanks!

**Comment by yariksav** [comment]
fixed in 0.3.7
https://github.com/yariksav/vuetify-dialog/commit/ef9e2801a51472d968afb235c8a8e4a67faa22e8
