### ISSUE TITLE
Bug or incorrect parameters

### ISSUE THREAD

**Issue by nikitachernih** [yariksav/vuetify-dialog#35]
Hello.
Apparently I found a bug, or I don’t understand which parameters should be substituted.

Привет.
Видимо, я нашел баг, или же не понимаю какие параметры стоит подставить

 this.$dialog.notify.success('Test notification', {
                    position: 'bottom-right',
                    timeout: 5000
                })
![1](https://user-images.githubusercontent.com/51114188/58465253-7c602f80-8161-11e9-9675-1966990e0d03.JPG)

**Comment by yariksav** [comment]
duplicate https://github.com/yariksav/vuetify-dialog/issues/102, will fix
