### ISSUE TITLE
Typescript `message` and `notify` are missing `success` method

### ISSUE THREAD

**Issue by allochi** [yariksav/vuetify-dialog#36]
Hi,

Thanks a lot for this wonderful library, just pointing out that the TypeScript types are missing `success` method for `message` and `notify`

**Comment by yariksav** [comment]
Thank you, @allochi, can you make a PR?

**Comment by allochi** [comment]
Done, it's PR #37

**Comment by yariksav** [comment]
Thanks! Please try v0.3.6
