### ISSUE TITLE
No show Color & Icon

### ISSUE THREAD

**Issue by ShawshankLin** [yariksav/vuetify-dialog#38]
This code works, but no show icons and color

my config

import Vuetify from "vuetify";
import VuetifyDialog from "vuetify-dialog";
Vue.use(Vuetify);
Vue.use(VuetifyDialog, {
  confirm: {
    actions: {
      false: "取消",
      true: {
        text: "确定",
        color: "primary"
      }
    },
    icon: false, // to disable icon just put false
    width: 500
  },
  warning: {},
  error: {},
  prompt: {}
});

my code
this.$dialog.confirm({
        text: "Do you realy want to delete item?",
        title: "Warning",
        actions: {
          false: "No",
          true: {
            color: "red",
            text: "Yes I do",
            handle: () => {
              return new Promise(resolve => {
                setTimeout(resolve, 3000);
              });
            }
          }
        }
      });

![QQ截图20190529211645](https://user-images.githubusercontent.com/16248686/58560155-1bb31e80-8257-11e9-9e7f-00036abffc50.png)

**Comment by yariksav** [comment]
try to use this.$dialog.warning({...}). And also .error, .info

**Comment by ShawshankLin** [comment]
Thanks！
