### ISSUE TITLE
Demo codesandbox source code?

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [yariksav/vuetify-dialog#39]
Hello, I am very interested in seeing the source code for the CodeSandbox demo for the dialogs ("Show card", "Show login" etc) as I want to make a custom dialog with a template and I'm not understanding the documentation.  The code for the dialog examples would be extremely helpful but I can't seem to find it anywhere.

**Comment by yariksav** [comment]
See here https://codesandbox.io/s/ppx57r3nnj

**Comment by WhatFreshHellIsThis** [comment]
Ahh..that's how it works, thank you.  I thought there must be some way to do that but couldn't seem to find it.  Maybe you could put a link on that demo page to the source code for others who are not familiar with codesandbox's url scheme?

**Comment by yariksav** [comment]
Thank you, @WhatFreshHellIsThis, I'll take it into account ) I supposed it's obvious
