### ISSUE TITLE
SandBox example error

### ISSUE THREAD

**Issue by kl3sk** [yariksav/vuetify-dialog#4]
Hello,

You have typo in your sandbox examples

### Confirmation : confirmation
```javascript
 let res = await this.$dialog.warning('Test confirmation, {
    text: 'Test confirmation',
    title: 'Title'
  })
```
Seems to be
```javascript
 let res = await this.$dialog.warning( {
    text: 'Test confirmation',
    title: 'Title'
  })
```
### Notification
Missing quotes
### Toast
Missing quotes

<hr />

Unless that it works as expected 😃

**Comment by yariksav** [comment]
Hi, @kl3sk! Thank you for the issue, i've fixed sandbox.

**Comment by kl3sk** [comment]
The quote error remain in the Toast example
