### ISSUE TITLE
Compatibility with Vuetify 2.0

### ISSUE THREAD

**Issue by AlbertoMolero** [yariksav/vuetify-dialog#43]
Hey guys, 

I like the idea of this module and I'd like to use it for one of my projects. The problem is that I am working on the Vuetify 2.0 Beta since it should be released soon and it has breaking changes on a few of the components you are using. 

I was wondering if you guys are working on this or planning to do so in the near future. If not I might fix a few things and do a pull request.

**Comment by yariksav** [comment]
Hi, @AlbertoMolero! Thank you for issue. I haven't investigate changes of vuetify 2.0, and it would be great if you will make PR or at least describe them in comments

**Comment by yariksav** [comment]
Closed via #46
