### ISSUE TITLE
Broken compatibility with Nuxt

### ISSUE THREAD

**Issue by kuyh** [yariksav/vuetify-dialog#44]
"0.3.8, update bili and config" release brakes compatiability with Nuxt.

![image](https://user-images.githubusercontent.com/6227732/61024762-a0ae5d80-a3e9-11e9-9fa3-533a74de70b8.png)

compiled file is like this;
```
node_modules/vuetify-dialog/dist/index.js
'use strict';

function _interopDefault (ex) { return (ex && (typeof ex === 'object') && 'default' in ex) ? ex['default'] : ex; }

var Vuedl = _interopDefault(require('vuedl/src/index'));
var styleInject = _interopDefault(require('../node_modules/style-inject/dist/style-inject.es.js'));
```

and occurs Cannot find module '../node_modules/style-inject/dist/style-inject.es.js'
looks like bili 4.8.0 bug in some circumstance.

**Comment by yariksav** [comment]
Hi, @kuyh. It's problem with rollup-plugin-postcss, I investigated and cannot remove this for now, i've tried all configs of bili and postcss... Maybe you will have idea. Or return to ver 0.3.6 and later I will investigate this
Also I've found this issue https://github.com/egoist/rollup-plugin-postcss/issues/165

**Comment by yariksav** [comment]
Can you try vuetify-dialog@0.4.0-beta.1 ? (note: now css you need install manually)

**Comment by kuyh** [comment]
thank you @yariksav .

0.4.0-beta.2 works well :)
