### ISSUE TITLE
Nuxt & Veutify 2

### ISSUE THREAD

**Issue by fjbardelli** [yariksav/vuetify-dialog#48]
is  vuetify-dialog@next compatible with nuxt?
What is the configuration to make it go?

**Comment by yariksav** [comment]
it's described at https://github.com/yariksav/vuetify-dialog#%EF%B8%8F-usage-with-nuxtjs

**Comment by fjbardelli** [comment]
I use this config
  modules: [
    // Doc: https://axios.nuxtjs.org/usage
    '@nuxtjs/axios',
    ['vuetify-dialog/nuxt', { property: '$dialog' }]
  ],
and get this error in de browser

![Captura de pantalla de 2019-09-13 11-03-31](https://user-images.githubusercontent.com/3776014/64868993-cdb00400-d616-11e9-9243-e217385297d1.png)

**Comment by fjbardelli** [comment]
491/5000
segun nuxt el error esta

acanode_modules / vuetify-dialog / dist / vuetify-dialog.umd.js: 5:

`(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('vue'), require('vuetify/lib')) :
  typeof define === 'function' && define.amd ? define(['exports', 'vue', 'vuetify/lib'], factory) :
  (global = global || self, factory(global.VuetifyDialog = {}, global.Vue, global.Vuetify));
}(this, function (exports, Vue, lib) { 'use strict';`

**Comment by fjbardelli** [comment]
To solve the error, delete the following lines from the vuetify-dialog.umd.js file, lines 1 to 5

`function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('vue'), require('vuetify/lib')) :
  typeof define === 'function' && define.amd ? define(['exports', 'vue', 'vuetify/lib'], factory) :
  (global = global || self, factory(global.VuetifyDialog = {}, global.Vue, global.Vuetify));
}`

This made the app work, and start without the error and recover the basic functions of it.
I don't know what problems this can bring to the rest of the module's functions.

I am using the latest versions of Vue, NuxtJS and veutify, to develop.

**Comment by yariksav** [comment]
@fjbardelli, can you try vuetify-dialog@1.0.0-alpha.5 ?

**Comment by fjbardelli** [comment]
Yes, in the tests I did so far in the migration of an app to veutify 2, everything is working ok,

Thank you so much

**Comment by Neoscopia** [comment]
I still get the same error even with the latest version (vuetify-dialog@1.0.0-alpha.5).
I tried @fjbardelli "hack" but this doesn't work

**Comment by yariksav** [comment]
Did you try version 2.0.0-rc.1?

**Comment by Neoscopia** [comment]
> Did you try version 2.0.0-rc.1?

Yes, still got the same error with this version :
```js
Uncaught /project/node_modules/vuetify/lib/index.js:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { export * from './components';
                                                                                                                                                           ^^^^^^

SyntaxError: Unexpected token export
    at new Script (vm.js:85:7)
    at createScript (vm.js:266:10)
    at Object.runInThisContext (vm.js:314:10)
    at Module._compile (internal/modules/cjs/loader.js:766:26)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:851:10)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (internal/modules/cjs/loader.js:739:19)
    at require (internal/modules/cjs/helpers.js:14:16)
```
