### ISSUE TITLE
persistent dialogs

### ISSUE THREAD

**Issue by kl3sk** [yariksav/vuetify-dialog#5]
Hello,

Is there a way to make the dialog persistent like Vuetify does. And in general is it possible to pass options to Vuetify component ?

Thanks

**Comment by yariksav** [comment]
Hello @kl3sk !
Just add "persistent" param true. I've added persistent to an example
```js
  let res = await this.$dialog.warning({
    text: 'Test confirmation',
    title: 'Title',
    persistent: false
  })
```
Concerning to pass options: What kind of vuetify component do you want to pass options?

**Comment by kl3sk** [comment]
Thank you I tried in nested options that's why it doesn't work.

About other options, it was just a question for example using:
- no-click-animation
- full-width
- content-class
- transition
- and so on

This is just a question to know what and what is not available.

<em>Nota: I don't try them</em>

**Comment by yariksav** [comment]
The notifications have own global scope, where calculate their positions. Therefore its cannot be separated inside an other element instead of the whole window. 
Сoncerning other props - I will check this

**Comment by kl3sk** [comment]
Ho it is not possible, it's a pity that we can not attach especially notification inside a "custom box".
Because I use a lot of them to inform the user and it could be considered as SPAM.

**Comment by yariksav** [comment]
Perhaps toast could be shown in separated container

**Comment by kl3sk** [comment]
Ok I look into it (trying do add inside a vue projet from this repo but can't achieve). Close for now.
