### ISSUE TITLE
vuetify-dialog is not compatible with the latest version of @nuxtjs/vuetify [1.9.0] + nuxt [2.10.0]

### ISSUE THREAD

**Issue by yaroslavolekh** [yariksav/vuetify-dialog#51]
Please, install default nuxt project with vuetify nuxt module:
https://www.npmjs.com/package/@nuxtjs/vuetify

You'll see error messages like:
TypeError: Cannot read property 'dark' of undefined

And many errors related to oldest/removed properties usage. 

Thank you, for your work %)

**Comment by yariksav** [comment]
Please try npm i vuetify-dialog@next

**Comment by fjbardelli** [comment]
@yaroslavolekh Find de solutions?
