### ISSUE TITLE
How to specify default value in $dialog.prompt?

### ISSUE THREAD

**Issue by WindBridges** [yariksav/vuetify-dialog#55]
Vanilla window.prompt() can receive a second argument, that allows to show default value in the textbox. Is it possible with this component?

**Comment by yariksav** [comment]
try send `value` as param
```
const res = await this.$dialog.prompt({ value: 'test', text: 'test text' })

**Comment by WindBridges** [comment]
Works, thank you! 
But PhpStorm highlights `value` option as an error, since it missing in DialogConfirmOptions.

**Comment by yariksav** [comment]
I will added it to typescript specification, will be in new release
