### ISSUE TITLE
Receiving custom emited events

### ISSUE THREAD

**Issue by Berkmann18** [yariksav/vuetify-dialog#57]
I'm trying to build a `dialog` that takes a property (in my case a list of `pages`) then once the user clicks on one option, the `dialog` will then dispatch an event from the Vuex store and redirect to another page.
The problem is that `this.$store` and `this.$router` are visibly undefined when called in the `dialog`'s component (which is structured like `TestCard` on https://codesandbox.io/s/ppx57r3nnj) so I thought I'll try to emit an event called `useTemplate`, however having the following doesn't work:
```js
created() {
  this.$on('useTemplate', tmpl => {
    this.$store.dispatch('editPage', tmpl);
    this.$router.push('editor');
  });
}
```
This doesn't do anything
```
this.$dialog.show(TemplateSelector, {
  pages: this.pagesToUse,
 '@useTemplate': this.useTemplate //even using 'v-on:useTemplate' does nothing
});
```

How could I get the parent component to properly receive the event or even better, how could I get the component to have access to the store and router?

**Comment by yariksav** [comment]
You have to put $route and $store to *context* in initialization options (see docs). Nuxt plugin do it by itself

**Comment by Berkmann18** [comment]
Ooh! Thank you :smile:.
