### ISSUE TITLE
this.$dialog.info failing vs others

### ISSUE THREAD

**Issue by Berkmann18** [yariksav/vuetify-dialog#58]
I've got this working fine up to the point when I tried to use (taken from a **working** warning confirmation thing I have in the code):
```js
const reminder = await this.$dialog.info({
        title: 'Template creation',
        text: `Please remember to use the <code>{{yourVariableNameHere}}</code> syntax
        when adding variables (that will be filled as you create a page with said template)`,
        actions: {
          false: {
            color: 'error',
            text: 'Cancel'
          },
          true: {
            color: 'primary',
            text: 'OK'
          }
        }
      });
```
The above leads to errors, however replacing `info` with `warning`/`error` makes it work.
The only way it works is by doing the following:
```js
const reminder = await this.$dialog.confirm({
        type: 'info',
        title: 'Template creation',
        text: `Please remember to use the <code>{{yourVariableNameHere}}</code> syntax
        when adding variables (that will be filled as you create a page with said template)`,
        actions: {
          false: {
            color: 'error',
            text: 'Cancel'
          },
          true: {
            color: 'primary',
            text: 'OK'
          }
        }
      });
```

I've tried the same above two variants with `success` and it appears that this inconsistent behaviour also applies to that.

The demo subtly suggests that it's not a bug, however, this seems inconsistent (only allowing a part of the `type`s one way and allowing all `type`s in another) and possibly _not intended_?

**Comment by yariksav** [comment]
Resolved in 2.0.12.in https://github.com/yariksav/vuetify-dialog/commit/57bfbbeb47e8604ab3c400bbb6e7bc06ae707f1b
