### ISSUE TITLE
Dialog into alert

### ISSUE THREAD

**Issue by kl3sk** [yariksav/vuetify-dialog#6]
Is there a way to make a dialog as an alert, I tried:

```javascript
 let res = await this.$dialog.confirm({
    text: 'Do you realy want to delete item?',
    title: 'Warning',
    actions: {
      false: 'Ok',
      true: {}
      }
    }
  }
```
This way `false` button appears empty

```javascript
 let res = await this.$dialog.confirm({
    text: 'Do you realy want to delete item?',
    title: 'Warning',
    actions: {
      false: 'Ok',
      true: false
      }
    }
  }
```
Throw an error.

Extra: Is there an option to align the button (independently will be the best) like `left`, `right`, `center` and/or with `margin/padding`.

Ps: I use your plugin a lot, thank you for you work 😄

**Comment by yariksav** [comment]
Just put only one action in array (or object)
actions: ['Ok']
Or
actions: {close: 'ok'}

You can put 3 or more actions. True and false is not necessary, it just for returns user choice

**Comment by kl3sk** [comment]
I'll try it tomorrow thank you
