### ISSUE TITLE
Possibility to use a component in a dialog

### ISSUE THREAD

**Issue by thebspin** [yariksav/vuetify-dialog#60]
I've tried looking through the docs and the src code but i don't think this is an option right now.
I would like to be able to use a component inside of a dialog window.
This way i could style the input fields to to match the rest of my application and i could also ask for more then 1 input fields for example.
I think this would be a really nice feature to have.

**Comment by yariksav** [comment]
import YourComponent from '...'
...
this. res = await this.$dialog.showAndWait(YourComponent, { params })
or if you don't need to wait for results:
this.$dialog.show(YourComponent, { params })

**Comment by thebspin** [comment]
Ah i actually found the `.show()` but i thought i should not use it since it has 0 styling.
I expected there to be atleast the styling for the modal border and background color but i guess that's also something you might want to replace with your own component right?

**Comment by yariksav** [comment]
this behavior is on purpose, because now it more flexible. you have to cover your component with v-card for border and background

**Comment by thebspin** [comment]
I see thanks! Am i right by saying that using the `.showAndWait` method there is no way for me to control the width of the dialog?

**Comment by thebspin** [comment]
Also i am having a hard time how to get my custom component data back to the response (the `this.res` in your example). Could you explain me how to do this? After i am done i could also make  PR to update the readme with this info

**Comment by yariksav** [comment]
Yes, for close dialog just call this.$emit('submit') in component
