### ISSUE TITLE
Cannot access $store within dialog

### ISSUE THREAD

**Issue by davbaron** [yariksav/vuetify-dialog#65]
I have created a sign-in dialog form, similar to the one in the sandbox. I would like to call my api service, however I need certain information (the url) from my vuex $store. Within the signIn component I declare a computed item to read the appropriate value from the $store, however I receive an error stating that the $store is undefined.

I did some research into this type of condition and found a thread for another product, Buefy, which is similar to Vuetify. It has a 'modal' widget that can host a component, probably similar in some ways to vuetify-dialog. Here is the link:  [https://github.com/buefy/buefy/issues/55]

In the thread is a recommendation to set the 'parent' of the modal to 'this', which they say will allow the modal component to have access to:  devTools, $store and $router.  I am not sure if this is related to vuetify-dialog, however I have noticed that the vue devTools plug-in for Chrome does not currently 'see' the vuetify-dialog object.

I am sure I am not the only dev who needs to have a modal dialog/form, and needs to have logic (methods) on that component put and get data from a vuex store. I'm hoping someone has gone thru this and can help.

Thank you.

**Comment by davbaron** [comment]
I re-read thru many of the previous issues for this plug-in and found the solution.  I had to add 'store' to the 'context block' within the Vue.use(VuetifyDialog section of my main.js file.  All works fine now.

Thank you again.

**Comment by yariksav** [comment]
yes, thank you
