### ISSUE TITLE
The demo with Vuetify 2 is broken

### ISSUE THREAD

**Issue by DannyFeliz** [yariksav/vuetify-dialog#66]
Hi,

The demo with Vuetify 2 is broken, could not fetch version for vuetify-dialog@0.4.0-beta.1.
[https://ppx57r3nnj.codesandbox.io/](https://ppx57r3nnj.codesandbox.io/)
![image](https://user-images.githubusercontent.com/5460365/77601682-caf56c00-6ee1-11ea-9f82-d4756ba40f0b.png)

**Comment by jonasrdm** [comment]
Still broken

![image](https://user-images.githubusercontent.com/2208017/78609581-56072800-7839-11ea-8e57-aa802116dcf9.png)

**Comment by Stenfrank** [comment]
Here you can validate the demo:

https://codesandbox.io/s/ppx57r3nnj?file=/src/main.js

Just adjust the package versions and test the other versions
