### ISSUE TITLE
Module JS

### ISSUE THREAD

**Issue by fjbardelli** [yariksav/vuetify-dialog#69]
It is possible to use the dialog box to ask for a code in a JS module, without a graphical interface.
I'm using it like this

    let res = await this.$dialog.prompt({
        text: 'Sucurity Code',
        title: 'code'
    })

and I answer this answer

TypeError: "this.$dialog is undefined"

**Comment by yariksav** [comment]
Something wrong with you component installation. Please read docs or see examples. Thanks
