### ISSUE TITLE
How to set icon in confirm dialog?

### ISSUE THREAD

**Issue by joweste** [yariksav/vuetify-dialog#74]
Hi, I just installed t5his component in Vuejs 2.0 and I id like to set an icon in the dialog.
I am using the next, but no icon is showing:
await this.$dialog.confirm({
        text: "Apaga registro?",
        title: "Confirmação",
        icon: "warning",
        actions: {
          false: "Não",
          true: {
            text: "Sim, eu quero",
            color: "red",
            handle: () => {
              return new Promise((resolve) => {
                setTimeout(resolve, 3000);
              });
            },
          },
        },
      });
    },

**Comment by yariksav** [comment]
Hi, @joweste. You have to provide **type** parameter
type: 'warning' // or 'info', 'error',...
or use as this.$dialog.warning(...)

**Comment by joweste** [comment]
I am confuse. Then, where icon property is used?
