### ISSUE TITLE
Please tell me how to use Show() method options

### ISSUE THREAD

**Issue by kenshinLost** [yariksav/vuetify-dialog#75]
Hi, 
I want to display a component using the show() method, but I don’t know that how to set options to receive $emit event from the component

for  example:
"JCategoryEditor" is a children component
submit(val) {
    this.$emit("event", val)
}

and this is parent component
this.$dialog.show(JCategoryEditor, {
      item: item,
      event: xxxxx // ??????
    })

**Comment by laurent-brisbois** [comment]
I have similar question : How to pass props using the `show()` method ?

So far I have : `this.$dialog.show(<name_of_the_dialog_component>)`

How to pass props to the dialog component ?

**Comment by yariksav** [comment]
Hi, @kenshinLost, you cannot use events in dialog, because it shows separatly and doesn't  parent component.
For achieve this you can send param as function and call it in component
this.$dialog.show(JCategoryEditor, {
item: item,
event: () => {
  console.log(arguments)
}
})

JCategoryEditor:
```
props: {
  event: Function
},
methods: {
submit(val) {
  this.event(val)
}
}
```
