### ISSUE TITLE
[BUG] Fix this typo to prevent bugs

### ISSUE THREAD

**Issue by laurent-brisbois** [yariksav/vuetify-dialog#76]
Hi there !

There may be bugs caused by this typo :

https://github.com/yariksav/vuetify-dialog/blob/228d823c97976f5c8a955bdbbe6d7ea62a18f211/src/components/Confirm.vue#L66

**Comment by yariksav** [comment]
Hi, @laurent-brisbois, thank you, I will fix it

**Comment by yariksav** [comment]
fixed
