### ISSUE TITLE
Using in TypeScript project.

### ISSUE THREAD

**Issue by avenmore** [yariksav/vuetify-dialog#8]
Error message on `import VuetifyDialog from 'vuetify-dialog';`

Could not find a declaration file for module 'vuetify-dialog'. '.../node_modules/vuetify-dialog/dist/vuetify-dialog.cjs.js' implicitly has an 'any' type.

If I add a .d.ts file with "declare module 'vuetify-dialog';" this error goes away. Is this the correct thing to do?

**Comment by yariksav** [comment]
Closed by #9

**Comment by felixyin** [comment]
import Vue from 'vue'
import Vuetify, { VSnackbar, VDialog, VCard, VCardTitle, VCardActions, VCardText, VSpacer, VBtn } from 'vuetify/lib'
import 'vuetify/src/stylus/app.styl'

Vue.use(Vuetify, {
  iconfont: 'md',
  components: {
// here, must be import, and will success
    VSnackbar,
    VDialog,
    VCard,
    VCardTitle,
    VCardActions,
    VCardText,
    VSpacer,
    VBtn,
  }
})

import VuetifyDialog from 'vuetify-dialog'
Vue.use(VuetifyDialog)
