### ISSUE TITLE
Error with maximum call stack exceeded

### ISSUE THREAD

**Issue by joweste** [yariksav/vuetify-dialog#81]
I am getting the next error: "Maximum call stack exceeded". I have seen it: https://github.com/vuetifyjs/vuetify/issues/5633. But I still have the error. I don´t know if it is the same problem. I use this dialog in many vues of my app. But, in this vue, I am getting this error.
     I am using vuetify with vuetify-dialog
     Is there some fix to it?
     const res = await this.$dialog.confirm({
        text: "Confirma Agendamento?",
        title: "Confirmação",
        // icon: "warning",
        type: "warning",
        actions: {
          false: "Não",
          true: {
            text: "Sim, eu quero",
            color: "primary",
          },
        },
      });
      if (res) {
        ////
      }
![image](https://user-images.githubusercontent.com/30800736/84546530-e5b4d100-acd7-11ea-85d5-b4bf764d431a.png)

**Comment by Esniper90** [comment]
i have same issue too @yariksav

**Comment by yariksav** [comment]
fixed in ec34eadffcfef468c2ed5a0723a4de7bc7a9f42c
please use vuetify-dialog@2.0.4
