### ISSUE TITLE
Warning in dialog.message

### ISSUE THREAD

**Issue by joweste** [yariksav/vuetify-dialog#83]
Hi, I am get the next warning with this code, from your samples:
 
this.$dialog.message.info("Registro criado com sucesso", {
            position: "top-right",
          });

![image](https://user-images.githubusercontent.com/30800736/84923217-51fb5000-b09d-11ea-8a4b-ee1350c0287c.png)

**Comment by yariksav** [comment]
please update to version 2.0.6
