### ISSUE TITLE
console.ts?522c:33 [Vuetify] Unable to locate target [data-app]

### ISSUE THREAD

**Issue by mean-cj** [yariksav/vuetify-dialog#87]
Hello @yariksav 

after update i will found warning on dev 
ref https://github.com/yariksav/vuetify-dialog/issues/82

```
console.ts?522c:33 [Vuetify] Unable to locate target [data-app]

found in

 <VDialog>
       <Root>
```

  | consoleWarn | @ | console.ts?522c:33
-- | -- | -- | --
  | initDetach | @ | index.ts?3875:142
  | mounted | @ | index.ts?3875:82
  | invokeWithErrorHandling | @ | vue.runtime.esm.js?2b0e:1854
  | callHook | @ | vue.runtime.esm.js?2b0e:4219
  | insert | @ | vue.runtime.esm.js?2b0e:3139
  | invokeInsertHook | @ | vue.runtime.esm.js?2b0e:6346
  | patch | @ | vue.runtime.esm.js?2b0e:6565
  | Vue._update | @ | vue.runtime.esm.js?2b0e:3945
  | updateComponent | @ | vue.runtime.esm.js?2b0e:4060
  | get | @ | vue.runtime.esm.js?2b0e:4479
  | Watcher | @ | vue.runtime.esm.js?2b0e:4468
  | mountComponent | @ | vue.runtime.esm.js?2b0e:4073
  | Vue.$mount | @ | vue.runtime.esm.js?2b0e:8415
  | show | @ | vuetify-dialog.esm.js?83df:518
  | show | @ | vuetify-dialog.esm.js?83df:754
  | eval | @ | vuetify-dialog.esm.js?83df:771
  | eval | @ | auth.firebase.js?360e:75
  | Promise.catch (async)

Thank you for your fixed

**Comment by yariksav** [comment]
Sorry, but here is no information or code

**Comment by 123hjq** [comment]
you can place <v-app> into app.vue

```
<template>
  <v-app>
    <transition>
      <router-view></router-view>
    </transition>
  </v-app>
</template>
```

**Comment by yariksav** [comment]
Closed, because no additional information provided
