### ISSUE TITLE
message position doesn't work

### ISSUE THREAD

**Issue by lyrbet** [yariksav/vuetify-dialog#89]
Hello

my message position doesn't work for me
```
Vue.use(VuetifyDialog, {
  context: {
    vuetify
  },
  toast: {
    //position: "top"
    position: "center"
  }
});
```
Why can't use `center`

thank you.

**Comment by mean-cj** [comment]
try

```
   toast: {
          position: 'top-center'
        }
```

**Comment by lyrbet** [comment]
@mean-cj it doesn't work too
this is example https://codesandbox.io/s/vuetify-demo-zs6b7?file=/src/main.js
i want positions the snackbar in the center of the screen, (x and y axis).
in the [vuetify document](https://vuetifyjs.com/en/components/snackbars/), the Snackbar component has this props(centered),but it also doesn't work

**Comment by yariksav** [comment]
it works correctly https://codesandbox.io/s/vuetify-demo-9xwcp?file=/src/main.js
just use any or combination of: top bottom right left
example: position: 'top left' or if you want centered top - use just 'top'

**Comment by lyrbet** [comment]
like this ,the center of the screen

![IMG_0461](https://user-images.githubusercontent.com/43900052/87704676-57000c00-c7cf-11ea-82e8-7bf0f24e07c4.JPG)

**Comment by yariksav** [comment]
it should be enhancement. I will keep in mind this
