### ISSUE TITLE
Property '$dialog' does not exist when using vue-property-decorator.

### ISSUE THREAD

**Issue by avenmore** [yariksav/vuetify-dialog#9]
In my Main.ts file I have:

```
import VuetifyDialog from 'vuetify-dialog';
Vue.use(VuetifyDialog);
```

And in my App (or any other) component:

```
<script lang="ts">
    import { Component, Vue } from 'vue-property-decorator';
    @Component
    export default class App extends Vue {
        private SomeFunction() {
            this.$dialog.error({
                  ^^^^^
```
But get "Property '$dialog' does not exist."

What am I missing to get this property on any Vue instance?

**Comment by yariksav** [comment]
Hi, @avenmore 

I don't have good experience with typescript, This issue need to investigate.
I've created [code sandbox](https://codesandbox.io/s/zrpj8jr67p) to reproduce bug, but seems this module works fine

Please check this and let me know

**Comment by yariksav** [comment]
Also in [documentation](https://vuejs.org/v2/guide/typescript.html#Augmenting-Types-for-Use-with-Plugins) tells 
I have to add file dialog.d.ts with code:
```ts
// 1. Make sure to import 'vue' before declaring augmented types
import Vue from 'vue'

// 2. Specify a file with the types you want to augment
//    Vue has the constructor type in types/vue.d.ts
declare module 'vue/types/vue' {
  // 3. Declare augmentation for Vue
  interface Vue {
    $dialog: object
  }
}

```

**Comment by avenmore** [comment]
Thank you. The code sandbox works, however, if I add this .d.ts file there are still problems in VSCode.

```
this.$dialog.error({
             ^^^^
```
Property 'error' does not exist on type 'object'.

I think it will be necessary to add an interface for 'dialog' too. Also there is still a problem with the import of vuetify-dialog so all these types need to be included under some kind of module export. I'm afraid that I'm new to this too and couldn't get it right myself.

As a work-around I am using `(this as any).$dialog.error({` which doesn't produce any ts errors.

**Comment by yariksav** [comment]
Can you show me .d.ts file?

**Comment by avenmore** [comment]
I created a .d.ts file with exactly the code you showed in comment 3. This worked so that $dialog was recognized, but I'm sorry, I don't know how to declare an interface or module for everything else. I will continue to try to see if I can understand what is needed.

**Comment by yariksav** [comment]
Hi, @avenmore ✌️!
Please install version 0.1.4 and check is correct implementation of typescript
all must work without (this as any) and without your dialog.d.ts file

If something will not work - please let me know  😊

**Comment by yariksav** [comment]
THank you, @avenmore. Can you check v0.1.5?

**Comment by avenmore** [comment]
I'm afraid the same error on `Vue.use(VuetifyDialog);` is still reported. The array error is fixed.

**Comment by yariksav** [comment]
Thank you for your help, because I don't use typescript for now. Please check version 0.1.6

**Comment by avenmore** [comment]
Almost there :) `Vue.use(VuetifyDialog);` and `this.$dialog.error()` are now working with no errors. However, I also then tried to use `this.$dialog.notify.info()` and `this.$dialog.message.info()`, but get the following errors:

```
29:17 Argument of type '{ position: string; timeout: number; }' is not assignable to parameter of type 'DialogMessageOptions'.
  Object literal may only specify known properties, and 'position' does not exist in type 'DialogMessageOptions'.
    27 |
    28 |                 this.$dialog.notify.info('Test notification', {
  > 29 |                     position: 'top-right',
       |                                ^^^^^^^^^
    30 |                     timeout: 5000,
    31 |                 });
    32 |

34:17 Argument of type '{ position: string; }' is not assignable to parameter of type 'DialogMessageOptions'.
  Object literal may only specify known properties, and 'position' does not exist in type 'DialogMessageOptions'.
    32 |
    33 |                 this.$dialog.message.info('Test', {
  > 34 |                     position: 'top-left',
       |                                ^^^^^^^^
    35 |                 });
    36 |
```

Think you just need to specify this property on the DialogMessageOptions interface.

**Comment by yariksav** [comment]
Nice, @avenmore! Please check v0.1.7 :)

**Comment by avenmore** [comment]
Perfect! :) Thank you for your components and for taking the time to learn and create the Typescript types. I'm looking forward to using them.

Hope I don't become a pest but will create more issues if I notice anything (like I see the font of notify is different to the font of the message).

**Comment by yariksav** [comment]
Thank you, @avenmore for your help!!! 👍 
It's would be awesome if you will take involvement to improve the module, create new issues or PR

I wrote module [vuedl](https://github.com/yariksav/vuedl), which take all logic on self, and vuetify-dialog - is only implementation it in vuetify. Also vuedl can be used in any framework

By this.$dialog.show(YourComponent) you can open in modal any type of component, also you can preload asyncDatas before show and use any layouts... Need to write documentation

Typescript was new for me and I decided to move my projects to it soon
