### ISSUE TITLE
Cannot read property hasAttribute of undefined

### ISSUE THREAD

**Issue by wimil** [yariksav/vuetify-dialog#91]
```javascript
this.$dialog.notify.info("Test notification", {
        position: "top-right",
        timeout: 5000
      });
```
![image](https://user-images.githubusercontent.com/54213518/88190572-0d188b00-cc00-11ea-9a06-331ff092a313.png)

vuetify-dialog@2.0.8
vuetify@2.3.5
nuxt@2.13.3

**Comment by yariksav** [comment]
Hi, @wimil, this bug is in vuetify 2.3.5, I already opened issue: https://github.com/vuetifyjs/vuetify/issues/11903, and the fixed it and will be at next version, just temporary rollback to 2.3.4
