### ISSUE TITLE
context from other nuxt modules is not passed to dialog

### ISSUE THREAD

**Issue by jorgv** [yariksav/vuetify-dialog#94]
I discovered that other modules registered in nuxt were not passed to the dialog instance, for example i18n, axios, auth:

![image](https://user-images.githubusercontent.com/32174909/88454509-7bfc1b00-ce70-11ea-87ad-2c21cfcf9052.png)

but after I found out that this only happens if the vuetify-dialog is registered after other modules in nuxt.config.js

  modules: [
    // Doc: https://axios.nuxtjs.org/usage
    '@nuxtjs/axios',
    '@nuxtjs/auth',
    'nuxt-i18n',
    'vuetify-dialog/nuxt',
  ],

To fix it just needed to register the module at the beginning: 

  modules: [
    'vuetify-dialog/nuxt',
    '@nuxtjs/axios',
    '@nuxtjs/auth',
    'nuxt-i18n'
  ],

Just leaving this issue as reference for anyone who encounters this issue.

**Comment by disjointed** [comment]
Hey, that really did help, thank you.
BUT, registering the module at the beginning still has undefined context when using `fetch () {}`:
```
async fetch () {
	console.log(this); // no context here
},
```

**Comment by yariksav** [comment]
asyncData and fetch call before vue component create. Therefore there never will be **this** inside. Please read nuxt docs.  
For this reason you have context as first argument. Like fetch(ctx) ...

**Comment by disjointed** [comment]
@yariksav 
Well I did actually read the docs, and, according to them, you **do** have access to `this` inside `fetch` hook, because it is called _after_ the `created` hook.
Here's a [good article about this](https://nuxtjs.org/blog/understanding-how-fetch-works-in-nuxt-2-12/#fetch-hook-and-nuxt-lifecycle)

**Comment by disjointed** [comment]
> @yariksav
> Well I did actually read the docs, and, according to them, you **do** have access to `this` inside `fetch` hook, because it is called _after_ the `created` hook.
> Here's [a good article about this](https://nuxtjs.org/blog/understanding-how-fetch-works-in-nuxt-2-12/#fetch-hook-and-nuxt-lifecycle).

So... no response on that?
