### ISSUE TITLE
Using as an exported method to show the Alert globally

### ISSUE THREAD

**Issue by shariful2011** [yariksav/vuetify-dialog#99]
I am using vuetify-dialog@nuxt. I want to use the alert component as an exported method as I have to call it in several places with several arguments. Below is my code.

I am using the latest version: 2.0.10

In nuxt.config.js
`['vuetify-dialog/nuxt', { property: '$dialog' }]`

```
const showNotification = (aMsg, aIsError) => {
  if (!aIsError) {
    this.$dialog.message.success(aMsg, {
      position: "bottom-left",
      icon: "mdi-alert-circle-outline",
      border: "left",
    });
  } else {
    this.$dialog.message.error(aMsg, {
      position: "bottom-left",
      icon: "mdi-alert-circle-outline",
      border: "left",
    });
  }
}

export default showNotification;
```
Uses:
`import showNotification from "@/utils/notification";`

For Calling it I used as below
`showNotification(response.data.message, false);`

But I got this error message

![image](https://user-images.githubusercontent.com/634779/91455880-72693700-e8a4-11ea-8751-fbac8a3db214.png)

How to solve this?

**Comment by yariksav** [comment]
This issue not related with module vuetify-dialog. You have to study usage **this** in arrow functions

Than you have to write 
```
const showNotification = function (aMsg, aIsError) {
```

or use it like
```
showNotification(response.data.message, false).bind(this);
```

**Comment by yariksav** [comment]
Hi, @shariful2011 , I updated comment, added call(this...) and fixed example with bind(this)

**Comment by shariful2011** [comment]
Thanks for your help. Though I had one solution, is to add one extra param as obj in my exported module and call it as showNotification(error.request, true, this.$dialog);

**Comment by yariksav** [comment]
it's not the best decision and practice

try to rewrite file as
```
const showNotification = function (aMsg, aIsError) {
  if (!aIsError) {
    this.$dialog.message.success(aMsg, {
      position: "bottom-left",
      icon: "mdi-alert-circle-outline",
      border: "left",
    });
  } else {
    this.$dialog.message.error(aMsg, {
      position: "bottom-left",
      icon: "mdi-alert-circle-outline",
      border: "left",
    });
  }
}

export default showNotification;
```

or 

```
showNotification.call(this, response.data.message, false);
```

**Comment by shariful2011** [comment]
I did change my code after got your new solution.
